electrification_data = 'src/electrification/loads-latest.csv'
roa_matrix = 'src/enduse/components-latest.csv'
noaa_folder = 'src/weather/noaa/%s.csv'
feeder_comp = 'src/feeder/composition-latest.csv'
aws_link = 'https://s3-us-west-1.amazonaws.com/load-composition-data.slacgismo.org/weather/noaa/%s.csv'
